version: '3.7'

services:
  nginx:
    depends_on:
      - api
    build: ./nginx

  api:
    depends_on:
      - db-postgres
    build: ./app
    command: gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: .env

  db-postgres:
    image: postgres:11.0-alpine
    environment:
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: db_api
    ports:
      - 5433:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
