version: '3.1'

services:

  flask:
      build: .
      environment:
        - PYTHONPATH=/celeryapp
      command: "python /celeryapp/app/run.py"
      ports:
          - 5000:5000
      links:
          - redis
          - celery
          - mailhog
      volumes:
          - ./app:/celeryapp/app:ro
      networks:
          - backend

  celery:
      build: .
      command: "celery -A app --config app.celeryconfig worker"
      user: nobody
      links:
          - redis
      volumes:
          - ./app:/celeryapp/app:ro
      networks:
          - backend

  redis:
      image: redis
      networks:
          - backend
      ports:
        - 6379:6379

  mailhog:
      image: mailhog/mailhog
      ports:
        - 8025:8025
      networks:
          - backend

networks:
  backend:
    name: backend